safe:        false
auto:        false
server:      false
server_port: 4000
baseurl:    /
url: http://localhost:4000

paginate: 5

source:      .
destination: ./_site
plugins:     ./_plugins

future:      true
lsi:         false
pygments:    true
markdown:    maruku
permalink:   /:year/:month/:day/:title
